sudo: false
language: rust
cache: cargo
rust:
- beta
- stable
- nightly
matrix:
  include:
  - rust: nightly-2017-10-09
    env: CLIPPY_VERS="0.0.165"
    before_script: |
      [[ "$(cargo +nightly-2017-10-09 clippy --version)" != "$CLIPPY_VERS" ]] && \
      cargo +nightly-2017-10-09 install clippy --vers "$CLIPPY_VERS" --force || true
    script: |
      cargo +nightly-2017-10-09 clippy -- -D warnings
  - rust: nightly-2017-10-09
    env: RUSTFMT_VERS="0.2.8"
    before_script: |
      [[ "$(cargo +nightly-2017-10-09 fmt -- --version)" != "$RUSTFMT_VERS"* ]] && \
      cargo +nightly-2017-10-09 install rustfmt-nightly --vers "$RUSTFMT_VERS" --force || true
    script: |
      cargo +nightly-2017-10-09 fmt --all -- --write-mode=diff
before_script:
- |
  which cargo-coverage && which cargo-coveralls || cargo install --force cargo-travis &&
  export PATH=$HOME/.cargo/bin:$PATH
script:
- |
  cargo test -- --test-threads=1 &&
  cargo bench
notifications:
  email:
    on_success: never
branches:
  only:
    - master
    - staging
    - trying
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
